CREATE DATABASE bob;
USE bob;

CREATE USER 'Mayor'@'localhost' IDENTIFIED BY 'pass';#С этим пользователем работает KakaoBobServer
GRANT ALL PRIVILEGES ON bob.* TO 'Mayor'@'localhost';

CREATE USER 'xtrabackup'@'localhost' IDENTIFIED BY 'pass';#Пользователь для бэкапа бд
GRANT BACKUP_ADMIN, RELOAD, LOCK TABLES, PROCESS, REPLICATION CLIENT ON *.* TO 'xtrabackup'@'localhost';
GRANT SELECT ON performance_schema.log_status TO 'xtrabackup'@'localhost';

CREATE USER 'bob_user_errors'@'%' IDENTIFIED BY 'KakaoBob_is_very_very_cool212';#К этому польователю подлкючается каждый клиент kakaobob приложения для проверки ошибок
GRANT SELECT ON bob.errors TO 'bob_user_errors'@'%';

CREATE TABLE users(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nickname VARCHAR(40) NOT NULL UNIQUE,
	password VARCHAR(128) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT NOW(),
	when_online DATETIME NOT NULL DEFAULT NOW(),
	path_avatar BLOB(4095) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;


CREATE TABLE files(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	filename VARCHAR(255) NOT NULL,
	path BLOB(4095) NOT NULL,
	size FLOAT(7,2) NOT NULL,#всего 7 цифр, из которых 2 после запятой
	sender_id INT NOT NULL,
	sent_at DATETIME NOT NULL DEFAULT NOW(),
	CONSTRAINT FOREIGN_FILES_SENDER_ID
	FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE photos(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	filename VARCHAR(255) NOT NULL,
	path BLOB(4095) NOT NULL,
	size FLOAT(7,2) NOT NULL,
	sender_id INT NOT NULL,
	sent_at DATETIME NOT NULL DEFAULT NOW(),
	CONSTRAINT FOREIGN_photos_SENDER_ID
	FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE friends(
	user_id INT NOT NULL,
	friend_id INT NOT NULL,
	CONSTRAINT FOREIGN_USER
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_FRIEND
	FOREIGN KEY(friend_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(user_id,friend_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE blocked_users(
	from_id INT NOT NULL,
	to_id INT NOT NULL,
	CONSTRAINT FOREIGN_BLOCKED_USERS_FROM
	FOREIGN KEY(from_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_BLOCKED_USERS_TO
	FOREIGN KEY(to_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(from_id,to_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE dialog(
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user1_id INT NOT NULL,
	user2_id INT NOT NULL,
	CONSTRAINT FOREIGN_DIALOG_USER1_ID
	FOREIGN KEY(user1_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_DIALOG_USER2_ID
	FOREIGN KEY(user2_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE(user1_id,user2_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE versions(
	id TINYINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	version FLOAT(3,1) NOT NULL UNIQUE,
	actual ENUM('n','y') NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE parties(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(60) NOT NULL,
	description BLOB(4095) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT NOW(),
	founder_id INT NOT NULL,
	path_avatar BLOB(4095) NOT NULL,
	CONSTRAINT FOREIGN_PARTIES_FOUNDER_ID
	FOREIGN KEY(founder_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE party_users(
	party_id INT NOT NULL,
	user_id INT NOT NULL,
	CONSTRAINT FOREIGN_PARTY_USERS_PARTY_ID
	FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_PARTY_USERS_USER_ID
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(party_id,user_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE party_admins(
	party_id INT NOT NULL,
	admin_id INT NOT NULL,
	CONSTRAINT FOREIGN_PARTY_ADMINS_PARTY_ID
	FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_PARTY_ADMINS_ADMIN_ID
	FOREIGN KEY(admin_id) REFERENCES party_users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(party_id,admin_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE companion_writes(
	user_id INT NOT NULL PRIMARY KEY,
	to_user_id INT NOT NULL,
	when_writed DATETIME NOT NULL DEFAULT NOW(),
	CONSTRAINT FOREIGN_COMPANION_WRITES_USER_ID
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_COMPANION_WRITES_TO_USER_ID
	FOREIGN KEY(to_user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE party_writes(
	user_id INT NOT NULL PRIMARY KEY,
	to_party_id INT,
	when_writed DATETIME NOT NULL DEFAULT NOW(),
	CONSTRAINT FOREIGN_PARTY_WRITES_USER_ID
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_PARTY_WRITES_TO_PARTY_ID
	FOREIGN KEY(to_party_id) REFERENCES parties(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE messages(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	to_id INT,
	from_id INT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT NOW(),
	updated_at DATETIME,
	text BLOB NOT NULL,
	file_id BIGINT,
	photo_id BIGINT,
	party_id INT,
	important BOOLEAN NOT NULL DEFAULT false,
	removable BOOLEAN NOT NULL DEFAULT true,
	CONSTRAINT FOREIGN_TO
	FOREIGN KEY(to_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_FROM
	FOREIGN KEY(from_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_MESSAGES_FILE_ID
	FOREIGN KEY(file_id) REFERENCES files(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_MESSAGES_PHOTO_ID
	FOREIGN KEY(photo_id) REFERENCES photos(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_MESSAGES_PARTY
	FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE who_saw_message(
	message_id BIGINT NOT NULL,
	who_saw_id INT NOT NULL,
	CONSTRAINT FOREIGN_WHO_SAW_MESSAGE_MESSAGE_ID
	FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN_WHO_SAW_MESSAGE_WHO_SAW_ID
	FOREIGN KEY(who_saw_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(message_id,who_saw_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE errors(
	user_id INT NOT NULL ,
	error VARCHAR(255),
	CONSTRAINT FOREIGN_VERSION_USER
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(user_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

INSERT INTO versions(version,actual) VALUES(1.0,'y');

